name: BungeeUtilCompanion
main: net.castlecraftmc.bungeeutilcompanion.BungeeUtilCompanion
version: 0.0.1
author: Frozen_Thunder
website: http://castlecraftmc.net
depend: [PlaceholderAPI, SocketMessenger]
commands:
  setspawn:
    permission: bungeeutil.get
    permission-message: You don't have the bungeeutil.setspawn permission required to use this command!
  spawn:
    permission: bungeeutil.spawn
    permission-message: You don't have the bungeeutil.spawn permission required to use this command!
  delspawn:
    permission: bungeeutil.delspawn
    permission-message: You don't have the bungeeutil.delspawn permission required to use this command!
  warp:
    permission: bungeeutil.warp
    permission-message: You don't have the bungeeutil.warp permission required to use this command!
  delwarp:
    permission: bungeeutil.delwarp
    permission-message: You don't have the bungeeutil.delwarp permission required to use this command!
  setwarp:
    permission: bungeeutil.setwarp
    permission-message: You don't have the bungeeutil.setwarp permission required to use this command!
  back:
    permission: bungeeutil.back
    permission-message: You don't have the bungeeutil.back permission required to use this command!
  tpa:
    permission: bungeeutil.tpa
    permission-message: You don't have the bungeeutil.tpa permission required to use this command!
    aliases: [tpr, teleportrequest]
  tp:
    permission: bungeeutil.tp
    permission-message: You don't have the bungeeutil.tp permission required to use this command!
    aliases: [teleport]
  tphere:
    permission: bungeeutil.tphere
    permission-message: You don't have the bungeeutil.tphere permission required to use this command!
    aliases: [teleporthere]
  tpaccept:
    permission: bungeeutil.tpaccept
    permission-message: You don't have the bungeeutil.tpaccept permission required to use this command!
  delcommand:
    permission: bungeeutil.delcommand
    permission-message: You don't have the bungeeutil.delcommand permission required to use this command!
  sethome:
    permission: bungeeutil.sethome
    permission-message: You don't have the bungeeutil.sethome permission required to use this command!
  delhome:
    permission: bungeeutil.delhome
    permission-message: You don't have the bungeeutil.delhome permission required to use this command!
  home:
    permission: bungeeutil.home
    permission-message: You don't have the bungeeutil.home permission required to use this command!
    aliases: [homes]

    